#!/usr/bin/env python
#
# https://github.com/pexpect/pexpect/blob/master/tests/fakessh/ssh

from __future__ import print_function

import getpass
import sys
PY3 = (sys.version_info[0] >= 3)
if not PY3:
    input = raw_input

server = sys.argv[-1]
if server == 'noserver':
    print('No route to host')
    sys.exit(1)

print("Mock SSH client for tests. Do not enter real security info.")

pw = getpass.getpass('password:')
if pw != 's3cret':
    print('Permission denied!')
    sys.exit(1)

prompt = "$"
while True:
    cmd = input(prompt)
    if cmd.startswith('PS1='):
        prompt = eval(cmd[4:]).replace('\$', '$')
    elif cmd == 'rosnode list':
        print('/rosout')
        print('/talker_8527_1511384376981')
    elif cmd == 'echo $?':
        print(0)
    elif cmd in ('exit', 'logout'):
        break
